### ISSUE TITLE
Release 2.0.0

### ISSUE THREAD

**Issue by ralphtheninja** [Level/leveldown-hyper#47]

**Comment by ralphtheninja** [comment]
We get the following errors on node 10 (when building binaries):

```
prebuild-ci info build electron abi 64
prebuild info begin Prebuild version 7.6.0
prebuild info build Preparing to prebuild leveldown-hyper@2.0.0 for electron 64 on linux-x64 using node-gyp
prebuild verb starting build process node-gyp 
prebuild verb execute node-gyp with `node index.js rebuild --target=3.0.0 --target_arch=x64 --runtime=electron --dist-url=https://atom.io/download/electron` 
prebuild WARN install got an error, rolling back install
prebuild ERR! configure error 
prebuild ERR! stack Error: 404 response downloading https://atom.io/download/electron/v3.0.0/iojs-v3.0.0-headers.tar.gz
prebuild ERR! stack     at Request.<anonymous> (/home/travis/build/Level/leveldown-hyper/node_modules/node-gyp/lib/install.js:214:14)
prebuild ERR! stack     at Request.emit (events.js:187:15)
prebuild ERR! stack     at Request.onRequestResponse (/home/travis/build/Level/leveldown-hyper/node_modules/node-gyp/node_modules/request/request.js:1074:10)
prebuild ERR! stack     at ClientRequest.emit (events.js:182:13)
prebuild ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:546:21)
prebuild ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
prebuild ERR! stack     at TLSSocket.socketOnData (_http_client.js:432:20)
prebuild ERR! stack     at TLSSocket.emit (events.js:182:13)
prebuild ERR! stack     at addChunk (_stream_readable.js:283:12)
prebuild ERR! stack     at readableAddChunk (_stream_readable.js:264:11)
prebuild ERR! not ok 
prebuild ERR! build Error: 404 response downloading https://atom.io/download/electron/v3.0.0/iojs-v3.0.0-headers.tar.gz
prebuild ERR! build     at Request.<anonymous> (/home/travis/build/Level/leveldown-hyper/node_modules/node-gyp/lib/install.js:214:14)
prebuild ERR! build     at Request.emit (events.js:187:15)
prebuild ERR! build     at Request.onRequestResponse (/home/travis/build/Level/leveldown-hyper/node_modules/node-gyp/node_modules/request/request.js:1074:10)
prebuild ERR! build     at ClientRequest.emit (events.js:182:13)
prebuild ERR! build     at HTTPParser.parserOnIncomingClient (_http_client.js:546:21)
prebuild ERR! build     at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
prebuild ERR! build     at TLSSocket.socketOnData (_http_client.js:432:20)
prebuild ERR! build     at TLSSocket.emit (events.js:182:13)
prebuild ERR! build     at addChunk (_stream_readable.js:283:12)
prebuild ERR! build     at readableAddChunk (_stream_readable.js:264:11)
```

**Comment by ralphtheninja** [comment]
Same happens on osx.

**Comment by vweevers** [comment]
Might be related to https://github.com/lgeiger/node-abi/pull/43

**Comment by ralphtheninja** [comment]
I was thinking that too, but the url looks odd `downloading https://atom.io/download/electron/v3.0.0/iojs-v3.0.0-headers.tar.gz`. Why `iojs` in there?

**Comment by ralphtheninja** [comment]
It has _something_ to do with this at least, if I run locally I have `node-abi@2.4.1` and then I get an error:

![screenshot from 2018-06-21 18-14-04](https://user-images.githubusercontent.com/308049/41731566-01be71e0-757f-11e8-85d6-716c1dec7953.png)

**Comment by ralphtheninja** [comment]
And when I re-install dependencies (getting `node-abi@2.4.2`):

![screenshot from 2018-06-21 18-16-42](https://user-images.githubusercontent.com/308049/41731683-4ffd54a2-757f-11e8-91bb-ec1dbfab7cda.png)

**Comment by vweevers** [comment]
There was another commit just 4 minutes ago: https://github.com/lgeiger/node-abi/commit/153811ab83ed52bfa929cd49adfcdc22f029790c

**Comment by ralphtheninja** [comment]
Makes sense, I guess `node-abi` should take care when updating until headers are hosted.

**Comment by ralphtheninja** [comment]
`node-abi@2.4.3` published, retrying node 10 builds

**Comment by ralphtheninja** [comment]
Also see https://github.com/lgeiger/node-abi/releases/tag/v2.4.3
